extends Node

enum STATUS {}

enum ELEMENT {STRIKE, PIERCE, SLASH, WATER, FIRE, WIND, FLORA, EARTH, LIGHT, SHADOW, THUNDER, COLD}

enum BATTLE_POSITION {PARTY_BACKLINE, PARTY_MIDLINE, PARTY_FRONTLINE, ENEMY_FRONTLINE, ENEMY_MIDLINE, ENEMY_BACKLINE}

enum TARGET_TYPE{SINGLE, MULTIPLE, ALL}

enum GAME_STATE{
	OVERWORLD,
	PARTY_MENU,
	
	BATTLE,
	BATTLE_MENU_NORMAL,
	BATTLE_MENU_SPECIALS,
	BATTLE_MENU_ITEMS,
	BATTLE_MENU_REPOSITION,
	
	BATTLE_NEW_TURN,
	BATTLE_ENEMY_TURN,
	
	BATTLE_SELECTING_TARGET_PARTY,
	BATTLE_SELECTING_TARGET_ENEMY,
	
	BATTLE_WON,
	BATTLE_LOST
}
