extends Node

enum STATUS {}

enum ELEMENT {STRIKE, PIERCE, SLASH, WATER, FIRE, WIND, FLORA, EARTH, LIGHT, SHADOW, COLD}

enum BATTLE_POSITION {PARTY_BACKLINE, PARTY_MIDLINE, PARTY_FRONTLINE, ENEMY_FRONTLINE, ENEMY_MIDLINE, ENEMY_BACKLINE}
